# Generated by Django 4.2.30 on 2026-05-05 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False, verbose_name='завершен')),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='баллы')),
                ('notes', models.TextField(blank=True, verbose_name='заметки')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_items', to='courses.lesson', verbose_name='урок')),
            ],
            options={
                'verbose_name': 'Элемент прогресса',
                'verbose_name_plural': 'Элементы прогресса',
                'ordering': ['-updated_at'],
            },
        ),
    ]
