# Generated by Django 4.2.30 on 2026-05-20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('progress', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressitem',
            name='grade',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='оценка'),
        ),
        migrations.CreateModel(
            name='QuarterGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.PositiveSmallIntegerField(choices=[(1, '1 четверть'), (2, '2 четверть'), (3, '3 четверть'), (4, '4 четверть')], default=1, verbose_name='четверть')),
                ('grade', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='оценка')),
                ('notes', models.TextField(blank=True, verbose_name='комментарий')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarter_grades', to='courses.course', verbose_name='курс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarter_grades', to=settings.AUTH_USER_MODEL, verbose_name='ученик')),
            ],
            options={
                'verbose_name': 'четвертная оценка',
                'verbose_name_plural': 'четвертные оценки',
                'ordering': ['course', 'user', 'quarter'],
                'unique_together': {('user', 'course', 'quarter')},
            },
        ),
    ]
