# Generated by Django 4.2.30 on 2026-05-20 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Вход в аккаунт'), ('signup', 'Регистрация аккаунта'), ('course_published', 'Публикация курса'), ('lesson_published', 'Публикация урока'), ('other', 'Прочее действие')], max_length=50, verbose_name='действие')),
                ('target_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='тип объекта')),
                ('target_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='ID объекта')),
                ('target_name', models.CharField(blank=True, max_length=255, verbose_name='название объекта')),
                ('details', models.JSONField(blank=True, null=True, verbose_name='детали')),
                ('ip_address', models.CharField(blank=True, max_length=45, verbose_name='IP адрес')),
                ('user_agent', models.CharField(blank=True, max_length=512, verbose_name='User-Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'Журнал действий',
                'verbose_name_plural': 'Журналы действий',
                'ordering': ['-created_at'],
            },
        ),
    ]
