# Generated by Django 4.2.30 on 2026-05-05 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aitmatov', '0001_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('is_aitmatov', models.BooleanField(default=False, verbose_name='курс Айтматова')),
                ('class_level', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='класс')),
                ('image', models.ImageField(blank=True, null=True, upload_to='courses/', verbose_name='изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлен')),
                ('aitmatov_theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='aitmatov.aitmatovtheme', verbose_name='тема Айтматова')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='subjects.subject', verbose_name='предмет')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='название')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='порядок')),
                ('content_type', models.CharField(choices=[('text', 'Текст'), ('video', 'Видео'), ('audio', 'Аудио')], default='text', max_length=20, verbose_name='тип контента')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='URL видео')),
                ('text_body', models.TextField(blank=True, verbose_name='текст урока')),
                ('quiz_enabled', models.BooleanField(default=False, verbose_name='включить тест')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course', verbose_name='курс')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ['course', 'order', 'title'],
            },
        ),
    ]
